//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryBooking
    {
        public int IDHisBook { get; set; }
        public int IDBook { get; set; }
        public string NameHisBook { get; set; }
        public System.DateTime DayCreateHisBook { get; set; }
    
        public virtual Booking Booking { get; set; }
    }
}
