//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int IDOrdD { get; set; }
        public int IDOrd { get; set; }
        public string NameService { get; set; }
        public int Quantity { get; set; }
        public int PriceOrdD { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime DayCreateOrdD { get; set; }
    
        public virtual OrderService OrderService { get; set; }
    }
}
