//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int IDService { get; set; }
        public string NameService { get; set; }
        public int PriceService { get; set; }
        public int IDCateSer { get; set; }
    
        public virtual CategoryService CategoryService { get; set; }
    }
}
